repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format


  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.20.0
    hooks:
      - id: django-upgrade
        args: ["--target-version", "4.2"]
