name: mobile_local

services:
  django:
    build:
      context: .
      dockerfile: compose/Dockerfile
    container_name: 'mobile_shop'
    command: /start
    restart: 'always'
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - main
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: 'mobile_db'
    restart: 'always'
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - main

networks:
  main:

volumes:
  postgres_data:
