# Generated by Django 5.1 on 2024-08-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('status', models.CharField(choices=[('موجود', 'موجود'), ('ناموجود', 'ناموجود')], max_length=10)),
                ('manufacture_country', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
            ],
        ),
    ]
